### ISSUE TITLE
Crash on  Prepare for Submission

### ISSUE THREAD

**Issue by Northwind877** [marsxcf/LocalizeX-Release#1]
Unfortunately, when I press Prepare for Submission, the app crashes:

<img width="227" alt="image" src="https://github.com/user-attachments/assets/6b235abf-9cfc-441f-ab29-d445e4ce4729">

<img width="252" alt="image" src="https://github.com/user-attachments/assets/f88f8921-03af-41e9-8c5b-5353c66fc499">

Do you receive the logs automatically? Otherwise I can send you the log file. 

Thank you

**Comment by marsxcf** [comment]
Sorry for that. 
Yes, I do receive the logs automatically through Firebase. I've got your crash log and I'll fix it ASAP.

**Comment by marsxcf** [comment]
It seems there was a hiccup with the configuration on Firebase Crashlytics. Could you please cause the app to crash one more time? It would be very helpful.

**Comment by Northwind877** [comment]
> It seems there was a hiccup with the configuration on Firebase Crashlytics. Could you please cause the app to crash one more time? It would be very helpful.

No problem, I crashed it again

**Comment by marsxcf** [comment]
Thx, but I did not receive the crash log. I think you might need to try a few more times.

**Comment by Northwind877** [comment]
Ok, did it 5 more times

**Comment by marsxcf** [comment]
> Ok, did it 5 more times

Thx, I've received the log and identified the issue; it will be fixed shortly.

**Comment by marsxcf** [comment]
The issue has been fixed and released, please upgrade to 0.11.1.

**Comment by Northwind877** [comment]
Thank you, it works now
